// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: error_reason.proto
// Protobuf C++ Version: 5.26.1

#ifndef GOOGLE_PROTOBUF_INCLUDED_error_5freason_2eproto_2epb_2eh
#define GOOGLE_PROTOBUF_INCLUDED_error_5freason_2eproto_2epb_2eh

#include <limits>
#include <string>
#include <type_traits>
#include <utility>

#include "google/protobuf/port_def.inc"
#if PROTOBUF_VERSION != 5026001
#error "Protobuf C++ gencode is built with an incompatible version of"
#error "Protobuf C++ headers/runtime. See"
#error "https://protobuf.dev/support/cross-version-runtime-guarantee/#cpp"
#endif
#include "google/protobuf/port_undef.inc"
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/arena.h"
#include "google/protobuf/arenastring.h"
#include "google/protobuf/generated_message_tctable_decl.h"
#include "google/protobuf/generated_message_util.h"
#include "google/protobuf/metadata_lite.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/repeated_field.h"  // IWYU pragma: export
#include "google/protobuf/extension_set.h"  // IWYU pragma: export
#include "google/protobuf/generated_enum_reflection.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"

#define PROTOBUF_INTERNAL_EXPORT_error_5freason_2eproto

namespace google {
namespace protobuf {
namespace internal {
class AnyMetadata;
}  // namespace internal
}  // namespace protobuf
}  // namespace google

// Internal implementation detail -- do not use these members.
struct TableStruct_error_5freason_2eproto {
  static const ::uint32_t offsets[];
};
extern const ::google::protobuf::internal::DescriptorTable
    descriptor_table_error_5freason_2eproto;
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google

namespace helloworld {
namespace v1 {
enum ErrorReason : int {
  GREETER_UNSPECIFIED = 0,
  USER_NOT_FOUND = 1,
  ErrorReason_INT_MIN_SENTINEL_DO_NOT_USE_ =
      std::numeric_limits<::int32_t>::min(),
  ErrorReason_INT_MAX_SENTINEL_DO_NOT_USE_ =
      std::numeric_limits<::int32_t>::max(),
};

bool ErrorReason_IsValid(int value);
extern const uint32_t ErrorReason_internal_data_[];
constexpr ErrorReason ErrorReason_MIN = static_cast<ErrorReason>(0);
constexpr ErrorReason ErrorReason_MAX = static_cast<ErrorReason>(1);
constexpr int ErrorReason_ARRAYSIZE = 1 + 1;
const ::google::protobuf::EnumDescriptor*
ErrorReason_descriptor();
template <typename T>
const std::string& ErrorReason_Name(T value) {
  static_assert(std::is_same<T, ErrorReason>::value ||
                    std::is_integral<T>::value,
                "Incorrect type passed to ErrorReason_Name().");
  return ErrorReason_Name(static_cast<ErrorReason>(value));
}
template <>
inline const std::string& ErrorReason_Name(ErrorReason value) {
  return ::google::protobuf::internal::NameOfDenseEnum<ErrorReason_descriptor,
                                                 0, 1>(
      static_cast<int>(value));
}
inline bool ErrorReason_Parse(absl::string_view name, ErrorReason* value) {
  return ::google::protobuf::internal::ParseNamedEnum<ErrorReason>(
      ErrorReason_descriptor(), name, value);
}

// ===================================================================



// ===================================================================




// ===================================================================


#ifdef __GNUC__
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
#ifdef __GNUC__
#pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)
}  // namespace v1
}  // namespace helloworld


namespace google {
namespace protobuf {

template <>
struct is_proto_enum<::helloworld::v1::ErrorReason> : std::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor<::helloworld::v1::ErrorReason>() {
  return ::helloworld::v1::ErrorReason_descriptor();
}

}  // namespace protobuf
}  // namespace google

// @@protoc_insertion_point(global_scope)

#include "google/protobuf/port_undef.inc"

#endif  // GOOGLE_PROTOBUF_INCLUDED_error_5freason_2eproto_2epb_2eh
