// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: error_reason.proto
// Protobuf C++ Version: 5.26.1

#include "error_reason.pb.h"

#include <algorithm>
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/extension_set.h"
#include "google/protobuf/wire_format_lite.h"
#include "google/protobuf/descriptor.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/reflection_ops.h"
#include "google/protobuf/wire_format.h"
#include "google/protobuf/generated_message_tctable_impl.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"
PROTOBUF_PRAGMA_INIT_SEG
namespace _pb = ::google::protobuf;
namespace _pbi = ::google::protobuf::internal;
namespace _fl = ::google::protobuf::internal::field_layout;
namespace helloworld {
namespace v1 {
}  // namespace v1
}  // namespace helloworld
static const ::_pb::EnumDescriptor* file_level_enum_descriptors_error_5freason_2eproto[1];
static constexpr const ::_pb::ServiceDescriptor**
    file_level_service_descriptors_error_5freason_2eproto = nullptr;
const ::uint32_t TableStruct_error_5freason_2eproto::offsets[1] = {};
static constexpr ::_pbi::MigrationSchema* schemas = nullptr;
static constexpr ::_pb::Message* const* file_default_instances = nullptr;
const char descriptor_table_protodef_error_5freason_2eproto[] ABSL_ATTRIBUTE_SECTION_VARIABLE(
    protodesc_cold) = {
    "\n\022error_reason.proto\022\rhelloworld.v1*:\n\013E"
    "rrorReason\022\027\n\023GREETER_UNSPECIFIED\020\000\022\022\n\016U"
    "SER_NOT_FOUND\020\001B\\\n\025dahua_sdk_ultimate.v1"
    "P\001Z/dahua_sdk_ultimate/api/dahua_sdk_ult"
    "imate/v1;v1\242\002\017APIHelloworldV1b\006proto3"
};
static ::absl::once_flag descriptor_table_error_5freason_2eproto_once;
const ::_pbi::DescriptorTable descriptor_table_error_5freason_2eproto = {
    false,
    false,
    197,
    descriptor_table_protodef_error_5freason_2eproto,
    "error_reason.proto",
    &descriptor_table_error_5freason_2eproto_once,
    nullptr,
    0,
    0,
    schemas,
    file_default_instances,
    TableStruct_error_5freason_2eproto::offsets,
    nullptr,
    file_level_enum_descriptors_error_5freason_2eproto,
    file_level_service_descriptors_error_5freason_2eproto,
};

// This function exists to be marked as weak.
// It can significantly speed up compilation by breaking up LLVM's SCC
// in the .pb.cc translation units. Large translation units see a
// reduction of more than 35% of walltime for optimized builds. Without
// the weak attribute all the messages in the file, including all the
// vtables and everything they use become part of the same SCC through
// a cycle like:
// GetMetadata -> descriptor table -> default instances ->
//   vtables -> GetMetadata
// By adding a weak function here we break the connection from the
// individual vtables back into the descriptor table.
PROTOBUF_ATTRIBUTE_WEAK const ::_pbi::DescriptorTable* descriptor_table_error_5freason_2eproto_getter() {
  return &descriptor_table_error_5freason_2eproto;
}
namespace helloworld {
namespace v1 {
const ::google::protobuf::EnumDescriptor* ErrorReason_descriptor() {
  ::google::protobuf::internal::AssignDescriptors(&descriptor_table_error_5freason_2eproto);
  return file_level_enum_descriptors_error_5freason_2eproto[0];
}
PROTOBUF_CONSTINIT const uint32_t ErrorReason_internal_data_[] = {
    131072u, 0u, };
bool ErrorReason_IsValid(int value) {
  return 0 <= value && value <= 1;
}
// @@protoc_insertion_point(namespace_scope)
}  // namespace v1
}  // namespace helloworld
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google
// @@protoc_insertion_point(global_scope)
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2
static ::std::false_type _static_init_ PROTOBUF_UNUSED =
    (::_pbi::AddDescriptors(&descriptor_table_error_5freason_2eproto),
     ::std::false_type{});
#include "google/protobuf/port_undef.inc"
