// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: dahua_sdk_ultimate.proto

#include "dahua_sdk_ultimate.pb.h"
#include "dahua_sdk_ultimate.grpc.pb.h"

#include <functional>
#include <grpcpp/support/async_stream.h>
#include <grpcpp/support/async_unary_call.h>
#include <grpcpp/impl/channel_interface.h>
#include <grpcpp/impl/client_unary_call.h>
#include <grpcpp/support/client_callback.h>
#include <grpcpp/support/message_allocator.h>
#include <grpcpp/support/method_handler.h>
#include <grpcpp/impl/rpc_service_method.h>
#include <grpcpp/support/server_callback.h>
#include <grpcpp/impl/server_callback_handlers.h>
#include <grpcpp/server_context.h>
#include <grpcpp/impl/service_type.h>
#include <grpcpp/support/sync_stream.h>
namespace dahua_sdk_ultimate {

static const char* DahuaManageService_method_names[] = {
  "/dahua_sdk_ultimate.DahuaManageService/SayHello",
  "/dahua_sdk_ultimate.DahuaManageService/SayHelloStreamReply",
  "/dahua_sdk_ultimate.DahuaManageService/SayHelloBidiStream",
};

std::unique_ptr< DahuaManageService::Stub> DahuaManageService::NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options) {
  (void)options;
  std::unique_ptr< DahuaManageService::Stub> stub(new DahuaManageService::Stub(channel, options));
  return stub;
}

DahuaManageService::Stub::Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options)
  : channel_(channel), rpcmethod_SayHello_(DahuaManageService_method_names[0], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_SayHelloStreamReply_(DahuaManageService_method_names[1], options.suffix_for_stats(),::grpc::internal::RpcMethod::SERVER_STREAMING, channel)
  , rpcmethod_SayHelloBidiStream_(DahuaManageService_method_names[2], options.suffix_for_stats(),::grpc::internal::RpcMethod::BIDI_STREAMING, channel)
  {}

::grpc::Status DahuaManageService::Stub::SayHello(::grpc::ClientContext* context, const ::dahua_sdk_ultimate::HelloRequest& request, ::dahua_sdk_ultimate::HelloReply* response) {
  return ::grpc::internal::BlockingUnaryCall< ::dahua_sdk_ultimate::HelloRequest, ::dahua_sdk_ultimate::HelloReply, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_SayHello_, context, request, response);
}

void DahuaManageService::Stub::async::SayHello(::grpc::ClientContext* context, const ::dahua_sdk_ultimate::HelloRequest* request, ::dahua_sdk_ultimate::HelloReply* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::dahua_sdk_ultimate::HelloRequest, ::dahua_sdk_ultimate::HelloReply, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_SayHello_, context, request, response, std::move(f));
}

void DahuaManageService::Stub::async::SayHello(::grpc::ClientContext* context, const ::dahua_sdk_ultimate::HelloRequest* request, ::dahua_sdk_ultimate::HelloReply* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_SayHello_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::dahua_sdk_ultimate::HelloReply>* DahuaManageService::Stub::PrepareAsyncSayHelloRaw(::grpc::ClientContext* context, const ::dahua_sdk_ultimate::HelloRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::dahua_sdk_ultimate::HelloReply, ::dahua_sdk_ultimate::HelloRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_SayHello_, context, request);
}

::grpc::ClientAsyncResponseReader< ::dahua_sdk_ultimate::HelloReply>* DahuaManageService::Stub::AsyncSayHelloRaw(::grpc::ClientContext* context, const ::dahua_sdk_ultimate::HelloRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncSayHelloRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::ClientReader< ::dahua_sdk_ultimate::HelloReply>* DahuaManageService::Stub::SayHelloStreamReplyRaw(::grpc::ClientContext* context, const ::dahua_sdk_ultimate::HelloRequest& request) {
  return ::grpc::internal::ClientReaderFactory< ::dahua_sdk_ultimate::HelloReply>::Create(channel_.get(), rpcmethod_SayHelloStreamReply_, context, request);
}

void DahuaManageService::Stub::async::SayHelloStreamReply(::grpc::ClientContext* context, const ::dahua_sdk_ultimate::HelloRequest* request, ::grpc::ClientReadReactor< ::dahua_sdk_ultimate::HelloReply>* reactor) {
  ::grpc::internal::ClientCallbackReaderFactory< ::dahua_sdk_ultimate::HelloReply>::Create(stub_->channel_.get(), stub_->rpcmethod_SayHelloStreamReply_, context, request, reactor);
}

::grpc::ClientAsyncReader< ::dahua_sdk_ultimate::HelloReply>* DahuaManageService::Stub::AsyncSayHelloStreamReplyRaw(::grpc::ClientContext* context, const ::dahua_sdk_ultimate::HelloRequest& request, ::grpc::CompletionQueue* cq, void* tag) {
  return ::grpc::internal::ClientAsyncReaderFactory< ::dahua_sdk_ultimate::HelloReply>::Create(channel_.get(), cq, rpcmethod_SayHelloStreamReply_, context, request, true, tag);
}

::grpc::ClientAsyncReader< ::dahua_sdk_ultimate::HelloReply>* DahuaManageService::Stub::PrepareAsyncSayHelloStreamReplyRaw(::grpc::ClientContext* context, const ::dahua_sdk_ultimate::HelloRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncReaderFactory< ::dahua_sdk_ultimate::HelloReply>::Create(channel_.get(), cq, rpcmethod_SayHelloStreamReply_, context, request, false, nullptr);
}

::grpc::ClientReaderWriter< ::dahua_sdk_ultimate::HelloRequest, ::dahua_sdk_ultimate::HelloReply>* DahuaManageService::Stub::SayHelloBidiStreamRaw(::grpc::ClientContext* context) {
  return ::grpc::internal::ClientReaderWriterFactory< ::dahua_sdk_ultimate::HelloRequest, ::dahua_sdk_ultimate::HelloReply>::Create(channel_.get(), rpcmethod_SayHelloBidiStream_, context);
}

void DahuaManageService::Stub::async::SayHelloBidiStream(::grpc::ClientContext* context, ::grpc::ClientBidiReactor< ::dahua_sdk_ultimate::HelloRequest,::dahua_sdk_ultimate::HelloReply>* reactor) {
  ::grpc::internal::ClientCallbackReaderWriterFactory< ::dahua_sdk_ultimate::HelloRequest,::dahua_sdk_ultimate::HelloReply>::Create(stub_->channel_.get(), stub_->rpcmethod_SayHelloBidiStream_, context, reactor);
}

::grpc::ClientAsyncReaderWriter< ::dahua_sdk_ultimate::HelloRequest, ::dahua_sdk_ultimate::HelloReply>* DahuaManageService::Stub::AsyncSayHelloBidiStreamRaw(::grpc::ClientContext* context, ::grpc::CompletionQueue* cq, void* tag) {
  return ::grpc::internal::ClientAsyncReaderWriterFactory< ::dahua_sdk_ultimate::HelloRequest, ::dahua_sdk_ultimate::HelloReply>::Create(channel_.get(), cq, rpcmethod_SayHelloBidiStream_, context, true, tag);
}

::grpc::ClientAsyncReaderWriter< ::dahua_sdk_ultimate::HelloRequest, ::dahua_sdk_ultimate::HelloReply>* DahuaManageService::Stub::PrepareAsyncSayHelloBidiStreamRaw(::grpc::ClientContext* context, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncReaderWriterFactory< ::dahua_sdk_ultimate::HelloRequest, ::dahua_sdk_ultimate::HelloReply>::Create(channel_.get(), cq, rpcmethod_SayHelloBidiStream_, context, false, nullptr);
}

DahuaManageService::Service::Service() {
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      DahuaManageService_method_names[0],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< DahuaManageService::Service, ::dahua_sdk_ultimate::HelloRequest, ::dahua_sdk_ultimate::HelloReply, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](DahuaManageService::Service* service,
             ::grpc::ServerContext* ctx,
             const ::dahua_sdk_ultimate::HelloRequest* req,
             ::dahua_sdk_ultimate::HelloReply* resp) {
               return service->SayHello(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      DahuaManageService_method_names[1],
      ::grpc::internal::RpcMethod::SERVER_STREAMING,
      new ::grpc::internal::ServerStreamingHandler< DahuaManageService::Service, ::dahua_sdk_ultimate::HelloRequest, ::dahua_sdk_ultimate::HelloReply>(
          [](DahuaManageService::Service* service,
             ::grpc::ServerContext* ctx,
             const ::dahua_sdk_ultimate::HelloRequest* req,
             ::grpc::ServerWriter<::dahua_sdk_ultimate::HelloReply>* writer) {
               return service->SayHelloStreamReply(ctx, req, writer);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      DahuaManageService_method_names[2],
      ::grpc::internal::RpcMethod::BIDI_STREAMING,
      new ::grpc::internal::BidiStreamingHandler< DahuaManageService::Service, ::dahua_sdk_ultimate::HelloRequest, ::dahua_sdk_ultimate::HelloReply>(
          [](DahuaManageService::Service* service,
             ::grpc::ServerContext* ctx,
             ::grpc::ServerReaderWriter<::dahua_sdk_ultimate::HelloReply,
             ::dahua_sdk_ultimate::HelloRequest>* stream) {
               return service->SayHelloBidiStream(ctx, stream);
             }, this)));
}

DahuaManageService::Service::~Service() {
}

::grpc::Status DahuaManageService::Service::SayHello(::grpc::ServerContext* context, const ::dahua_sdk_ultimate::HelloRequest* request, ::dahua_sdk_ultimate::HelloReply* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status DahuaManageService::Service::SayHelloStreamReply(::grpc::ServerContext* context, const ::dahua_sdk_ultimate::HelloRequest* request, ::grpc::ServerWriter< ::dahua_sdk_ultimate::HelloReply>* writer) {
  (void) context;
  (void) request;
  (void) writer;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status DahuaManageService::Service::SayHelloBidiStream(::grpc::ServerContext* context, ::grpc::ServerReaderWriter< ::dahua_sdk_ultimate::HelloReply, ::dahua_sdk_ultimate::HelloRequest>* stream) {
  (void) context;
  (void) stream;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}


}  // namespace dahua_sdk_ultimate

